#! /bin/sh

user=`whoami`
names=`finger $user | fgrep "ame:" | sed 's/.*: *\([^ ]*\)[^:]*/\1/'`
for name in ${names}; do break; done
echo "Hello $name, watch me make harmonics for the 2dF 100k survey."
echo "If this works, I will be impressed.  It may take a while to complete."

# to make verbose
quiet=
# to make quiet
#quiet=-q

# maximum harmonic number
lmax=20

mangledir=../../bin/

# North

if [ -z "$quiet" ]; then
    echo "===========================================";
    echo "                   NORTH                   ";
fi

# name of output file to contain 2dF 100k North polygons
npol=2df_north.pol

# -vo says to use old polygon ids, which are field numbers
echo "${mangledir}snap $quiet -vo ngp_fields.dat jnf"
${mangledir}snap $quiet -vo ngp_fields.dat jnf || exit
echo "${mangledir}snap $quiet -vo ngpholes.dat jnh"
${mangledir}snap $quiet -vo ngpholes.dat jnh || exit
# -n intersects holes with their parent fields
echo "${mangledir}poly2poly $quiet -n jnh jnf jnhf"
${mangledir}poly2poly $quiet -n jnh jnf jnhf || exit
echo "${mangledir}balkanize $quiet centres.ngp jnhf jnb"
${mangledir}balkanize $quiet centres.ngp jnhf jnb || exit
echo "${mangledir}weight $quiet -z2dF100k jnb jnw"
${mangledir}weight $quiet -z2dF100k jnb jnw || exit
echo "${mangledir}unify $quiet jnw $npol"
${mangledir}unify $quiet jnw $npol || exit
echo "Polygons for 2dF 100k North are in $npol"

# South

if [ -z "$quiet" ]; then
    echo "===========================================";
    echo "                   SOUTH                   ";
fi

# name of output file to contain 2dF 100k South polygons
spol=2df_south.pol

# -vo says to use old polygon ids, which are field numbers
echo "${mangledir}snap $quiet -vo sgp_fields.dat jsf"
${mangledir}snap $quiet -vo sgp_fields.dat jsf || exit
echo "${mangledir}snap $quiet -vo sgpholes.dat jsh"
${mangledir}snap $quiet -vo sgpholes.dat jsh || exit
# -n intersects holes with their parent fields
echo "${mangledir}poly2poly $quiet -n jsh jsf jshf"
${mangledir}poly2poly $quiet -n jsh jsf jshf || exit
echo "${mangledir}balkanize $quiet centres.sgp centres.ran jshf jsb"
${mangledir}balkanize $quiet centres.sgp centres.ran jshf jsb || exit
echo "${mangledir}weight $quiet -z2dF100k jsb jsw"
${mangledir}weight $quiet -z2dF100k jsb jsw || exit
echo "${mangledir}unify $quiet jsw $spol"
${mangledir}unify $quiet jsw $spol || exit
echo "Polygons for 2dF 100k South are in $spol"

# Harmonics

if [ -z "$quiet" ]; then
    echo "===========================================";
    echo "                 THE WORLD                 ";
fi

# name of output file to contain harmonics
wlm=2df.wlm

echo "${mangledir}harmonize $quiet -l$lmax $npol $spol $wlm"
${mangledir}harmonize $quiet -l$lmax $npol $spol $wlm || exit
echo "Harmonics for 2dF 100k mask up to l = $lmax are in $wlm"

# Map

# name of output file to contain map
map=2df.map

echo "${mangledir}map $quiet -w$wlm azel.dat $map"
${mangledir}map $quiet -w$wlm azel.dat $map || exit
echo "Map of 2dF 100k mask up to l = $lmax is in $map"

# Vertices

# name of output file to contain vertices
vert=2df.vrt

echo "${mangledir}poly2poly -ov $quiet $npol $spol $vert"
${mangledir}poly2poly -ov $quiet $npol $spol $vert || exit
echo "Vertices of 2dF 100k mask are in $vert"

# Graphics

# name of output file to contain graphics
grph=2df.grph

# number of points per (2 pi) along each edge of a polygon
pts_per_twopi=30

echo "${mangledir}poly2poly -og$pts_per_twopi $quiet $npol $spol $grph"
${mangledir}poly2poly -og$pts_per_twopi $quiet $npol $spol $grph || exit
echo "Data suitable for plotting polygons of the 2dF 100k mask are in $grph:"
echo "each line is a sequence of az, el points delineating the perimeter of a polygon."

# remove temporary files
rm j[ns]*

if [ -z "$quiet" ]; then
    echo "===========================================";
    echo "the universe?"
fi

if [ "$quiet" ]; then
    echo ""
    echo "If you'd like to repeat that with the sound on,"
    echo "please turn off the quiet button in 2df and try again."
fi
